### ISSUE TITLE
Title parameter in the config.toml

### ISSUE THREAD

**Issue by krissfr** [signal18/replication-manager#101]
Hi,

Currently we use the title parameter in config.toml to store the name of our customer (or the project name of our customer), but this parameter isn't display in the web UI (i guess never use in any files/programs).

Could it be possible to display the value of this parameter (if not empty) in the top of the web UI, next to the "Replication Manager Dashboard" message ?

Regards,

Krissfr

**Comment by tanji** [comment]
Yes, absolutely. I need to rework the config a lot because I plan to support multiple configurations in the same file. So that's already a plan.

**Comment by krissfr** [comment]
thank you :)

**Comment by tanji** [comment]
This is fixed in ef184f3d524b094c783f2ffa293b302dabcb3ece

This group of commits adds two new options:
`--config` and `--config-group`

The first option allows you to point to a configuration file path of your choice.
The second option allows configuration groups, e.g.:

```
[cluster2]
# options go here

[cluster3]
#options go here
```

replication-manager can now parse those groups when you start it with `--config-group=cluster2` for example, and this group will be indicated in the dashboard in the "Monitoring Group" section.
