### ISSUE TITLE
Failover/Switchover: Events status not updated

### ISSUE THREAD

**Issue by kdruelle** [signal18/replication-manager#103]
When a failover/switchover is performed and a new master is elected, MRM doesn't set Events Scheduler state on new master.

When old master is up again and switch in slave mode, Events Scheduler need to be turn Off are not updated neither.

**Comment by sysdljr** [comment]
Besides, every event status must update to enable on new master ,  default  event status is SLAVESIDE_DISABLED on slave.

**Comment by svaroqui** [comment]
Fix by last commit

**Comment by kdruelle** [comment]
Seams that commit 39d8e32283244e9123ed3768d3dbe0a0a13c5a68 fix this issue by update event_scheduler global variable.

Would not it be better to update Status on each event to SLAVESIDE_DISABLED ?

**Comment by sysdljr** [comment]
after slave switch to master , if event status is SLAVESIDE_DISABLED  then this event can't execute on scheduler is ON.

**Comment by svaroqui** [comment]
Humm, i don't get the issue if you have SLAVESIDE_DISABLED you should not have to do anything with replication manager , the event_scheduler is 0N on every nodes and only the master can execute the event ? Or is there an issue here ?

**Comment by sysdljr** [comment]
Yes,  Default master's event status is Enable and all slave's event status are  SLAVESIDE_DISABLED in mysql replication. and event execute once  only  on master.

reference link:
https://dev.mysql.com/doc/refman/5.7/en/create-event.html

example:
create event on master:
CREATE DEFINER=`root`@`localhost` EVENT `ev_test` ON SCHEDULE EVERY 1 HOUR STARTS '2016-11-27 14:18:00' ON COMPLETION PRESERVE **ENABLE** DO BEGIN  
INSERT IGNORE INTO test119 VALUES (1,100) ;
END 

on slave show:
create DEFINER=`root`@`localhost` EVENT `ev_test` ON SCHEDULE EVERY 1 HOUR STARTS '2016-11-27 14:18:00' ON COMPLETION PRESERVE **DISABLE ON SLAVE** DO BEGIN  
INSERT IGNORE INTO test119 VALUES (1,100) ;
END

After failover,  slave change to master ,  because event's status is SLAVESIDE_DISABLED,  only set event_scheduler=on,   all event still can't execute.  must modify event's status to Enable.
besides , old master change to slave ,  must   set event_scheduler=off. otherwise, old master's event still execute.  (This is not permit)

Before use MRM, we Manual execution these ,  could MRM automate execute these after failover or switchover? 
 Thanks.

**Comment by svaroqui** [comment]
Why don't you just do set sql_bin_log=0 in the event and have symetrics event on all nodes

**Comment by svaroqui** [comment]
just set sql_bin_log=0  need super privileges from definer

**Comment by svaroqui** [comment]
Fixed as part of last commit https://github.com/tanji/replication-manager/commit/c85d38c163d8fb1f2ff169387e8563401169903f
