### ISSUE TITLE
Error getting privileges for user X on server

### ISSUE THREAD

**Issue by King-Black** [signal18/replication-manager#167]
Hi, at the end of my log file you see the error:
"Error getting privileges for user repli on server 192.168.2.55:3316: sql: Scan error on column index 0: unsupported Scan,...to type *string Hint: Some lines were ellipsized, use -l to show in full."

Our configuration is
Master-Slave-Slave (MariaDB 10.1.22) and a MaxScale (2.1.4) Server with running replication-manager (1.0.2).

I have updated go to the newest version, but that doesn't help.

I have attached our config.toml and the replication-manager log file.

[config.toml.txt](https://github.com/tanji/replication-manager/files/1124795/config.toml.txt)

[replication-manager.log.txt](https://github.com/tanji/replication-manager/files/1124797/replication-manager.log.txt)

**Comment by tanji** [comment]
Hi,

usually that happens when your user is defined under the following form:
`user@'192.168.%'` and MRM can't parse it.

To avoid that, define your user as
`user@'192.168.%.%'`

Hope that helps

**Comment by King-Black** [comment]
Hi Tanji,
thanks for your answer.

The user ist defined as:
`user@192.168.2.58`.
I have tried it with `user@192.168.%.%` and it works. But why? That's not the way how it should work? I think it's only one adress from the server who works replication-manager?

Thanks for your help.

edit: With `user@192.168.2.%` it also works.

**Comment by tanji** [comment]
Hi King-Black,

In this case it's the replication user aka `repluser` in the configuration, this user is _not_ from the replication-manager server but is used to configure the replication from slaves to master (aka `CHANGE MASTER TO ... master_user= ... master_password=...`)

That's why `user@192.168.2.58` did not function in your case - I assume `192.168.2.58` is the IP address of your MRM server.
