### ISSUE TITLE
MySQL 8 GTID rejoin old master after failover is not working 

### ISSUE THREAD

**Issue by rajkumar-nms** [signal18/replication-manager#429]
Switch over only working in mysql-commercial-8.0.28 version. Replication manager not supports for fail over case in mysql 8.0.28

**Comment by svaroqui** [comment]
Hi, can you send us you mysql and repman conf so that i can work out the issue i never worked on group replication hoping your not using this yet ?

**Comment by rajkumar-nms** [comment]
**Master my.cnf**
server-id = 1
log-bin = mysql-bin
binlog_format = row
gtid-mode=ON
enforce-gtid-consistency=ON
log-slave-updates

**Slave my.cnf**
server-id = 2
log-bin = mysql-bin
relay-log = relay-log-server
read-only = ON
gtid-mode=ON
enforce-gtid-consistency=ON
log-slave-updates

**RepMan configuration** 
db-servers-hosts = "192.168.9.127:3307,192.168.11.97:6306"
db-servers-prefered-master = "192.168.9.127:3307"
db-servers-credential = "repluser:12qwaszx"
db-servers-connect-timeout = 1
replication-credential = "repluser:12qwaszx"

**Comment by svaroqui** [comment]
Thanks i'll keep you posted

**Comment by svaroqui** [comment]
Do you mean rejoin old leader does not work correct? 
But failover take place a new leader is elected and remaining slave is attach to it , can you join replication-manager log  ?

**Comment by rajkumar-nms** [comment]
Yes you are correct rejoin is not working 
![Screenshot from 2022-05-05 19-36-13](https://user-images.githubusercontent.com/104970320/166941228-0f6bbd88-f207-4bfd-8eb2-d216ace46d3e.png)

**Comment by svaroqui** [comment]
Hello, can you reproduce on 2.2.21 ?

**Comment by svaroqui** [comment]
Ok i was abe to reproduce, and i confirmed this has been working by accident and was never implemented correctly with mysql GTID , the failure of show slave status switch code  use to execute jump to a function that parse the joiner binlog via show bin log events ans this is broken for 8.x.

I'm working now on extracting MySQL GTID and compair position with the one saved in the crash info. For MySQL using GTID it is saved on elected leader via replication informartion Executed_Gtid_Set: 23055335-d202-11ec-a95f-06bbd81cfcc3:1-6. 

This does not work currently because the MySQL GTID is saved with a hash of uuid while replication-manager use the server_id for MariaDB GTID , so far i get the correct position or the joiner but not yet for the crash and i don't understand why yet . 

Also when code is correct and found difference in position it can switch to SST and SST can use direct mysqldump pipe mysql client 

Because now mysql send an error if you pass the password by argument many backup have been broken , so i recently change the code to inject password via go pipe stdin , this work for regular backup but not for backup + pipe as the stdin is already used to inject the dump blocking the code in a go-routine waiting for password validation. 

Any idea are welcome on that last point and should be easy to produce a test case that run a select 1; pipe to the mysql client using password via STDIN as well.
