### ISSUE TITLE
Minimal privileges for db-servers user

### ISSUE THREAD

**Issue by Thorsieger** [signal18/replication-manager#511]
Hello,

I search on the documentation and on readmes but i couldn't find what are the minimal privileges pour the user identified as "db-servers-credential" in the config file.

I do not want to use root, and don't want to give full access to an user if it doesn't needs to.

I only find this (closed) issue : https://github.com/signal18/replication-manager/issues/26, but privileges SUPER, REPLICATION CLIENT and RELOAD are not enough.

**Comment by tanji** [comment]
@Thorsieger hello, could you clarify what you mean by "not enough"? What issues is it causing exactly?

**Comment by svaroqui** [comment]
Hi based on this list of global 

[Global Privileges](https://mariadb.com/kb/en/grant/#global-privileges)
[BINLOG ADMIN](https://mariadb.com/kb/en/grant/#binlog-admin)
[BINLOG MONITOR](https://mariadb.com/kb/en/grant/#binlog-monitor)
[BINLOG REPLAY](https://mariadb.com/kb/en/grant/#binlog-replay)
[CONNECTION ADMIN](https://mariadb.com/kb/en/grant/#connection-admin)
[CREATE USER](https://mariadb.com/kb/en/grant/#create-user)
[FEDERATED ADMIN](https://mariadb.com/kb/en/grant/#federated-admin)
[FILE](https://mariadb.com/kb/en/grant/#file)
[GRANT OPTION](https://mariadb.com/kb/en/grant/#grant-option)
[PROCESS](https://mariadb.com/kb/en/grant/#process)
[READ_ONLY ADMIN](https://mariadb.com/kb/en/grant/#read_only-admin)
[RELOAD](https://mariadb.com/kb/en/grant/#reload)
[REPLICATION CLIENT](https://mariadb.com/kb/en/grant/#replication-client)
[REPLICATION MASTER ADMIN](https://mariadb.com/kb/en/grant/#replication-master-admin)
[REPLICA MONITOR](https://mariadb.com/kb/en/grant/#replica-monitor)
[REPLICATION REPLICA](https://mariadb.com/kb/en/grant/#replication-replica)
[REPLICATION SLAVE](https://mariadb.com/kb/en/grant/#replication-slave)
[REPLICATION SLAVE ADMIN](https://mariadb.com/kb/en/grant/#replication-slave-admin)
[SET USER](https://mariadb.com/kb/en/grant/#set-user)
[SHOW DATABASES](https://mariadb.com/kb/en/grant/#show-databases)
[SHUTDOWN](https://mariadb.com/kb/en/grant/#shutdown)
[SUPER](https://mariadb.com/kb/en/grant/#super)

the only 2 i'm not using yet are :
[FEDERATED ADMIN](https://mariadb.com/kb/en/grant/#federated-admin)
[FILE](https://mariadb.com/kb/en/grant/#file)

But it may change change in the futur for example i may use connect to read the errors log file and report back in GUI


Those ones also optionals
[SET USER](https://mariadb.com/kb/en/grant/#set-user)
[GRANT OPTION](https://mariadb.com/kb/en/grant/#grant-option)

This could be used when activating password rotation or when password management is delegated to  vault 


Since a time  i have disable  by default all schedulers and enforcement that would touch the database and you have the source code to check  that we are not leaking any sensible informations. 

Some data exchange could happen when using Cloud18 Portal options
dynamic config can be saved to our private gitlab after registration to it each user get an associated  group based on his email domain 

In this mode 
- config files is send to us but each credential option get encrypted with a key that you  need to generated and you should keep ownership
- the cpu and memory usage 
this mode enable to save and retrieve config  but on the long run to register a cluster to be commercialized  in our portal in DBAAS mode

**Comment by svaroqui** [comment]
Also if you give. root account you can offuscat password 

First generate a key on the default path 
```
Usage:
  replication-manager keygen [flags]

Flags:
  -h, --help             help for keygen
      --keypath string   Encryption key file path (default "/etc/replication-manager/.replication-manager.key")
      --overwrite        Overwrite the previous key
```

and later on replace occurence of the password in config via the result of following command 
```
 ./replication-manager-pro password "mysecretpassword"
Encrypted password hash: hash_c7602a5650136d66961079e8b4806ceb1da7b9647a038d7ae0411c7f3b867312
```

**Comment by Thorsieger** [comment]
Well, ok If the replication manager user needs almost all permissions to run correctly I will gave it. :'(
