### ISSUE TITLE
Replication manager is connecting with the wrong user to the database

### ISSUE THREAD

**Issue by Thorsieger** [signal18/replication-manager#525]
Hello !

While upgrading to repman 2.3.14 with vault as a secrets backend. I found out that the replication-manager program connect with the `replication-credential` and not `db-servers-credential`.

I noticed it because of a rights problem: on the database the user was the "repl" one.

part of my configuration :

```
        [Default]

        #Vault
        vault-server-addr="https://MY_VAULT_SERVER"
        vault-auth="approle"
        vault-role-id="REDACTED"
        vault-secret-id="REDACTED"

```

```
    [cluster400]
    title = "cluster400"

    vault-mode="config_store_v2"
    vault-mount="kvrepman"

    db-servers-hosts = "127.0.0.1:3306,127.0.0.1:3307,127.0.0.1:3308"
    db-servers-credential = "myd/db-400"
    replication-credential = "myd/db-400"
    db-servers-connect-timeout = 5
    db-servers-read-timeout = 15

```

using the log-level 7 I've found the configuration :

```
db-servers-credential:{repman:REDACTED repl:REDACTED}
replication-credential:{repl:REDACTED repl:REDACTED}
```

I think that repman only use the second value of this key

**Comment by Thorsieger** [comment]
i've maybe find the problem here : https://github.com/signal18/replication-manager/blob/develop/cluster/cluster_set.go#L671

I think it's need to be : GetVaultMonitorCredentials

**Comment by svaroqui** [comment]
Nice catch i'll try t review it thanks

**Comment by svaroqui** [comment]
Can you please write here you give this code under freebsd licence ?

**Comment by Thorsieger** [comment]
yep ! I give this code under freebsd license

**Comment by Thorsieger** [comment]
Do you have any ETA for the v2.3.15 milestone ? :)

Thank you !

**Comment by svaroqui** [comment]
Hello  Thorsieger  good to hear from you and thanks again for your contribution. 

This new release may be more or less verbose because we have added a per module verbosity level to better troubleshoot

We are hard working  adding new features like mysql 8.3 new GTID format support and also safe purging of binary logs based on a maximum disk size (could help to restore dump with active binlogs)  and fixing when backup binary log are enabled  to prevent purging when a slave is stopped or delayed , this will be for 2.3.16  milestone now :)
