### ISSUE TITLE
Data race and SIGSEGV

### ISSUE THREAD

**Issue by fmbiete** [signal18/replication-manager#546]
Full Version:  v2.3.19-1-g9bd2ef6d

Built from sources with "-race" to identify some issues, I also get a very early SIGSEGV
Shouldn't you be protecting the Cluster instance with some kind of mutex?

See attached
[out.log](https://github.com/signal18/replication-manager/files/14820690/out.log)
[config.toml.txt](https://github.com/signal18/replication-manager/files/14820698/config.toml.txt)

**Comment by ahfa92** [comment]
Hi @fmbiete,
Thank you for your feedback.

Do you have some insight on this case? This is an open source software and we welcome contributors.

**Comment by svaroqui** [comment]
Hi good catch we will try to improve on your analyze  there is a mutex  on the cluster class but we don't  always protect on it as the state machine is protected.

**Comment by svaroqui** [comment]
Ok digging into the race debugger we have fixed minor race issues that comes around service placement when doing provision indeed looking at the code concurrency we have very few done in concurrency 

**In the main cluster loop  cluster.go** 

We have Topology and Heartbeat that can run concurently 
```
                                 wg := new(sync.WaitGroup)
				wg.Add(1)
				go cluster.TopologyDiscover(wg)
				wg.Add(1)
				go cluster.Heartbeat(wg)
				wg.Wait()

```
But rejoined Following with  a concurrent execution  of refresh proxy and every 30 monitoring loop some non synchronized actions that could potentially be network driven  like found the agent nodes that are infos on physical hosts holding databases and proxies 
```
  	if !cluster.IsInFailover() {
						wg.Add(1)
						go cluster.refreshProxies(wg)

						if cluster.StateMachine.SchemaMonitorEndTime+60 < time.Now().Unix() && !cluster.StateMachine.IsInSchemaMonitor() {
							go cluster.MonitorSchema()
						}
						if cluster.Conf.TestInjectTraffic || cluster.Conf.AutorejoinSlavePositionalHeartbeat || cluster.Conf.MonitorWriteHeartbeat {
							cluster.InjectProxiesTraffic()
						}
						if cluster.StateMachine.GetHeartbeats()%30 == 0 {
							go cluster.initOrchetratorNodes()
							cluster.MonitorQueryRules()
							cluster.MonitorVariablesDiff()
							go cluster.ResticFetchRepo()
							cluster.IsValidBackup = cluster.HasValidBackup()
							go cluster.CheckCredentialRotation()
							cluster.CheckCanSaveDynamicConfig()
							cluster.CheckIsOverwrite()

						} else {
							cluster.StateMachine.PreserveState("WARN0093")
							cluster.StateMachine.PreserveState("WARN0084")
							cluster.StateMachine.PreserveState("WARN0095")
							cluster.StateMachine.PreserveState("WARN0101")
							cluster.StateMachine.PreserveState("ERR00090")
							cluster.StateMachine.PreserveState("WARN0102")
						}
						if !cluster.CanInitNodes {
							cluster.SetState("ERR00082", state.State{ErrType: "WARNING", ErrDesc: fmt.Sprintf(clusterError["ERR00082"], cluster.errorInitNodes), ErrFrom: "OPENSVC"})
						}
						if !cluster.CanConnectVault {
							cluster.SetState("ERR00089", state.State{ErrType: "WARNING", ErrDesc: fmt.Sprintf(clusterError["ERR00089"], cluster.errorConnectVault), ErrFrom: "OPENSVC"})
						}

						if cluster.StateMachine.GetHeartbeats()%36000 == 0 {
							cluster.ResticPurgeRepo()
						} else {
							cluster.StateMachine.PreserveState("WARN0094")
						}
						cluster.PrintDelayStat()
					}
					wg.Wait()
```
After that we manage the state machine to keep or remove states that changed during a monitoring loop  

In topology detection the database ping and refresh  (ping doing a refresh if database can connect)  are done concurrently  per server with the ignored server done first so that replication position will alway be more accurate  on non ignored nodes 
```
wg := new(sync.WaitGroup)
	if cluster.Conf.Hosts == "" {
		return errors.New("Can not discover empty cluster")
	}
	for _, server := range cluster.Servers {
		if server.IsIgnored() {
			wg.Add(1)
			go server.Ping(wg)
		}
	}
	wg.Wait()

	wg = new(sync.WaitGroup)
	for _, server := range cluster.Servers {
		if !server.IsIgnored() {
			wg.Add(1)
			go server.Ping(wg)
		}
	}
	wg.Wait()
```

Regarding database info concurrent code is trigger in refresh for long database operation 

```
	go server.JobBackupBinlogPurge(server.BinaryLogFilePrevious)
```
Only first one is not protected against multiple call 

```
	go server.GetPFSQueries()
	go server.GetSlowLogTable()
```
Are protected against concurrent code via local boolean and defer
```
        if server.IsInPFSQueryCapture {
		return
	}
	server.IsInPFSQueryCapture = true
	defer func() { server.IsInPFSQueryCapture = false }()
```

This one is not protected and is used to write metric to carbon local storage when graphite and metric enabled 
```
	go server.SendDatabaseStats()
```

In the next release we have added mutex protection on class  server and proxy   using lock unlock 
on the refresh code  so that concurrent refresh on same object is impossible 

I doubt it help but one important founding was made 

The failover code using switchover  code from API could have been run twice 
Note that we use the mutexed  state class to cancel refresh rejoin code 
``` 
func (SM *StateMachine) SetFailoverState() {
    SM.Lock()
    SM.InFailover = true
    SM.Unlock()
}
``` 

But the failover itself did not check before entering  so we added :
``` 
func (cluster *Cluster) MasterFailover(fail bool) bool {
	if cluster.GetTopology() == topoMultiMasterRing || cluster.GetTopology() == topoMultiMasterWsrep || cluster.GetTopology() == topoMultiMasterGrouprep {
		res := cluster.VMasterFailover(fail)
		return res
	}
	if cluster.IsInFailover() {
		cluster.LogModulePrintf(cluster.Conf.Verbose, config.ConstLogModGeneral, LvlInfo, "Cancel already in failover")
		return false
	}
```

**Comment by svaroqui** [comment]
Please test 2.3.20 and reopen if not fixed

**Comment by fmbiete** [comment]
I don't see the crash anymore, thank you!
