### ISSUE TITLE
Error with Monitor: Preferred master is not included in the hosts option

### ISSUE THREAD

**Issue by willcn** [signal18/replication-manager#56]
I don't quite understand this error message:
Preferred master is not included in the hosts option

wfong@willcn:~$ replication-manager monitor --hosts=127.0.0.1:3307,127.0.0.1:3308,127.0.0.1:3309 --user=root --rpluser=r  --http-server --http-root=go/src/github.com/mariadb-corporation/replication-manager/dashboard --autorejoin --prefmaster=127.0.0.1:3308,127.0.0.1:3309
2016/07/12 00:09:40 ERROR: Preferred master is not included in the hosts option
wfong@willcn:~$ replication-manager monitor --hosts=127.0.0.1:3307 --user=root --rpluser=r  --http-server --http-root=go/src/github.com/mariadb-corporation/replication-manager/dashboard --autorejoin --prefmaster=127.0.0.1:3308,127.0.0.1:3309
2016/07/12 00:11:35 ERROR: Preferred master is not included in the hosts option
wfong@willcn:~$ 

Not sure how to specify the hosts in my replication environment, and specify which hosts that I would like MRM to use as a master.

**Comment by tanji** [comment]
prefmaster works as documented:

Preferred candidate server for master failover, in host:[port] format

In the case above it does not work because you've specified multiple candidates. Prefmaster supports exactly one server spec (I should probably add a test for that).
If you want to ignore servers, use the --ignore-servers option.
