### ISSUE TITLE
add log_slave_updates checking along with log_bin

### ISSUE THREAD

**Issue by whatot** [signal18/replication-manager#81]
The log_slave_updates is needed when the slave will be promoted as a new master in most cases when use mrm. 
So I suggest add log_slave_updates checking along with log_bin.

**Comment by tanji** [comment]
@whatot log_slave_updates is not a requirement with MariaDB GTID. I run all my tests without it and it passes OK.
@svaroqui any opinion?

**Comment by whatot** [comment]
@tanji I run my one-master-two-slaves test with switchover and failover, in MariaDB GTID 10.0.17. It will go wrong without log_slave_updates.
what is your test environment?

**Comment by svaroqui** [comment]
Yes log_slave_updates is not needed but can be good to have in case you have additional slaves  at deeper level, such slaves can be pointed to any failable server manage by replication manager (MRM) 
Today such  topology are not manage by MRM and will not move or need configuration declaration of those extra slaves

**Comment by tanji** [comment]
Same as yours @whatot.
Do you have any process that's writing to the slaves?
What kind of GTID errors do you get?

**Comment by whatot** [comment]
@tanji Force to kill master when write to master, then failover or switchover, continue on the new master.
Without log_slave_updates, the process will fail.

**Comment by svaroqui** [comment]
Whatot we have only recently (TODAY) added github version inside the release numbering but would recommend you are running the last release, there is a small chance that the issue you  are seeing is not caused by log slave updates , we for example have fix important issue 26 days ago 
https://github.com/tanji/replication-manager/commit/1f016644cfd684ea6621afe6716a867d8a07330f

As all rpm and binaries have no github can you make sure you  reinstall  the last binaries of replication-manager before we dig  more with log slave updates  and your setting

**Comment by whatot** [comment]
I use the tanji's latest commit when test.
go get -u github.com/tanji/replication-manager

**Comment by svaroqui** [comment]
ok good to know

**Comment by svaroqui** [comment]
to you use semi-sync as explained in the doc

**Comment by whatot** [comment]
ok, I will try it, but it is not easy to change the sync in production.
thank you

**Comment by svaroqui** [comment]
It is also critical to check that no users writes with the super privileges because it will overwrite the read-only flag , we would like to drive maxscale 2.0.X to enable no writes to newly elected master before the replication queue is applied, this code should go before the first release
